[package]
name = "zec-sqlite-cli"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anyhow = "1"
bip0039 = { version = "0.12", features = ["std", "all-languages"] }
futures-util = "0.3"
gumdrop = "0.8"
prost = "0.13"
rayon = "1.7"
rusqlite = { version = "0.29", features = ["time"] }
orchard = { version = "0.9", default-features = false }
sapling = { package = "sapling-crypto", version = "0.2" }
schemer = "0.2"
secrecy = "0.8"
serde = "1.0"
time = "0.2"
tokio = { version = "1.21.0", features = ["fs", "macros", "rt-multi-thread", "signal"] }
toml = "0.8"
tonic = { version = "0.12", features = ["gzip", "tls-webpki-roots"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
zcash_address = {   git = "https://github.com/chainSafe/librustzcash", rev = "144bfca68cb9e8dc4de0011730bfe32f8406e591"}
zcash_client_backend = { git = "https://github.com/chainSafe/librustzcash", rev = "144bfca68cb9e8dc4de0011730bfe32f8406e591", features = ["lightwalletd-tonic", "orchard", "tor"] }
zcash_client_sqlite = { git = "https://github.com/chainSafe/librustzcash", rev = "144bfca68cb9e8dc4de0011730bfe32f8406e591", features = ["unstable", "orchard"] }
zcash_client_memory = { git = "https://github.com/chainSafe/librustzcash", rev = "144bfca68cb9e8dc4de0011730bfe32f8406e591", features = ["unstable", "orchard"] }
zcash_keys = {  git = "https://github.com/chainSafe/librustzcash", rev = "144bfca68cb9e8dc4de0011730bfe32f8406e591", features = ["unstable", "orchard"] }
zcash_primitives =  { git = "https://github.com/chainSafe/librustzcash", rev = "144bfca68cb9e8dc4de0011730bfe32f8406e591"}
zcash_proofs = {  git = "https://github.com/chainSafe/librustzcash", rev = "144bfca68cb9e8dc4de0011730bfe32f8406e591"}
zcash_protocol =  { git = "https://github.com/chainSafe/librustzcash", rev = "144bfca68cb9e8dc4de0011730bfe32f8406e591"}
zip321 =  { git = "https://github.com/chainSafe/librustzcash", rev = "144bfca68cb9e8dc4de0011730bfe32f8406e591" }

# Currency conversion
iso_currency = { version = "0.4", features = ["with-serde"] }
rust_decimal = "1"

# TUI
crossterm = { version = "0.27", optional = true, features = ["event-stream"] }
ratatui = { version = "0.26", optional = true }
roaring = { version = "0.10", optional = true }
tokio-util = { version = "0.7", optional = true }
tui-logger = { version = "0.11", optional = true, features = ["tracing-support"] }
subtle = "2.6.1"

[features]
default = ["transparent-inputs"]
transparent-inputs = [
    "zcash_client_sqlite/transparent-inputs",
]
tui = [
    "dep:crossterm",
    "dep:ratatui",
    "dep:roaring",
    "dep:tokio-util",
    "dep:tui-logger",
]
sqlite = []
memory = []

[patch.crates-io]
zip32 = { git = "https://github.com/zcash/zip32.git", branch = "diversifier_index_ord"}
