[package]
name = "zec-sqlite-cli"
version = "0.1.0"
edition = "2021"
rust-version = "1.70"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anyhow = "1"
bip0039 = { version = "0.12", features = ["std", "all-languages"] }
futures-util = "0.3"
gumdrop = "0.8"
prost = "0.13"
rayon = "1.7"
rusqlite = { version = "0.29", features = ["time"] }
orchard = { version = "0.9", default-features = false }
sapling = { package = "sapling-crypto", version = "0.2" }
schemer = "0.2"
secrecy = "0.8"
serde = "1.0"
time = "0.2"
tokio = { version = "1.21.0", features = ["fs", "macros", "rt-multi-thread", "signal"] }
toml = "0.8"
tonic = { version = "0.12", features = ["gzip", "tls-webpki-roots"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
zcash_address = "0.4"
zcash_client_backend = { version = "0.13", features = ["lightwalletd-tonic", "orchard", "tor"] }
zcash_client_sqlite = { version = "0.11", features = ["unstable", "orchard"] }
zcash_keys = { version = "0.3", features = ["unstable", "orchard"] }
zcash_primitives = "0.16"
zcash_proofs = "0.16"
zcash_protocol = "0.2"
zip321 = "0.1"

# Currency conversion
iso_currency = { version = "0.4", features = ["with-serde"] }
rust_decimal = "1"

# TUI
crossterm = { version = "0.28", optional = true, features = ["event-stream"] }
ratatui = { version = "0.28", optional = true }
roaring = { version = "0.10", optional = true }
tokio-util = { version = "0.7", optional = true }
tui-logger = { version = "0.12", optional = true, features = ["tracing-support"] }

[features]
default = ["transparent-inputs"]
transparent-inputs = [
    "zcash_client_sqlite/transparent-inputs",
]
tui = [
    "dep:crossterm",
    "dep:ratatui",
    "dep:roaring",
    "dep:tokio-util",
    "dep:tui-logger",
]
