[package]
name = "zec-sqlite-cli"
version = "0.1.0"
edition = "2021"
rust-version = "1.60"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anyhow = "1"
futures-util = "0.3"
gumdrop = "0.8"
prost = "0.12"
rayon = "1.7"
rusqlite = { version = "0.29", features = ["time"] }
schemer = "0.2"
secrecy = "0.8"
time = "0.2"
tokio = { version = "1.21.0", features = ["fs", "macros", "rt-multi-thread"] }
tonic = { version = "0.10", features = ["gzip", "tls-webpki-roots"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
zcash_client_backend = { version = "=0.10.0-rc.1", features = ["lightwalletd-tonic"] }
zcash_client_sqlite = { version = "=0.8.0-rc.1", features = ["unstable"] }
zcash_primitives = "=0.13.0-rc.1"
zcash_proofs = "=0.13.0-rc.1"
