[package]
name = "zec-sqlite-cli"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
anyhow = "1"
futures-util = "0.3"
gumdrop = "0.8"
prost = "0.11"
schemer = "0.2"
secrecy = "0.8"
tls-api-rustls = "0.6"
tokio = { version = "1.21.0", features = ["fs", "macros", "rt-multi-thread"] }
tonic = { version = "0.8", features = ["gzip", "tls-webpki-roots"] }
zcash_client_backend = { version = "0.6", features = ["lightwalletd-tonic"] }
zcash_client_sqlite = { version = "0.4", features = ["unstable"] }
zcash_primitives = "0.9"
zcash_proofs = "0.9"
